{{- if .Values.env }}
{{- if .Values.env.private }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ printf "sid-%s" .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    name: {{ .Values.name }}
  data:
    {{- range $name, $key := .Values.env.private }}
  - secretKey: {{ $name }}
    remoteRef:
      key: {{ $key }}
    {{- end }}
{{- end }}
{{- end }}
