{{ $releaseName := $.Values.name }}
{{ $servicePort := $.Values.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Values.name }}-{{ $.Values.environment }}
  name: {{ $.Values.ingress.name }}
  namespace: {{ printf "sid-%s" $.Values.namespace }}
spec:
  rules:
  - host: {{ $.Values.ingress.domain }}
    http:
      paths:
      {{- range $path := $.Values.ingress.paths}}
      - path: {{ $path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}
            port:
              number: {{ $servicePort }}
      {{- end }}
